export const AppText = {
   email_input: "Entrez votre email",
   password_input: "Entrez votre mot de passe",
   confirm_password_input: "Veuillez ressaisir votre mot de passe",
   name_childcare_input: "Entrez ne nom de la crèche",
   first_name_input: "Entrez votre prénom",
   last_name_input: "Entrez votre nom",
   address_input: "Entrez votre adresse",
   phone_number_input: "Entrez votre numero de telephone",
   maxChildren_input: "Entrez le nombre maximum d'enfants",
   opening_hours_input: "Entrez les heures d'ouverture",
   password_forgetten: "Mot de passe oublié?",
   register_redirection: "Vous n'avez pas de compte? Inscrivez-vous",
   login_redirection: "Vous avez déjà un compte? Connectez-vous",
   register_button: "S'inscrire",
   connexion_button: "Connexion",
   responsable_button: "Responsable",
   parent_button: "Parent",
   educatrice_button: "Educatrice",
   create_childcare_button: "Creer une crèche",
   create_parent_button: "Creer un parent",
   create_educatrice_button: "Creer une educatrice",
   manage_childcare_button: "Gerer ses crèches",
   manage_parent_button: "Gerer les parents",
   manage_educatrice_button: "Gerer les educatrices",
   create_button: "Creer",

   password_error: "Le mot de passe doit contenir au moins 8 caractères, une majuscule, un chiffre et un caractère spécial",
   password_required: "Le mot de passe est requis",
   confirm_password_required: "La confirmation du mot de passe est requise",
   password_not_match: "Les mots de passe ne correspondent pas",
   email_error: "L'email doit être au format valide",
   email_required: "L'email est requis",
   firstname_required: "Le prénom est requis",
   lastname_required: "Le nom est requis",
   name_required: "Le nom est requis",
   param_required: "Le parametre est requis",
   address_required: "L'adresse est requise",
   phone_required: "Le numéro de téléphone est requis",
   phone_number_error: "Le numéro de téléphone doit contenir 10 chiffres",
   invalid_credentials: "L'Email ou le mot de passe est incorrect",
   form_incorrect: "L'Email ou le mot de passe est incorrect",
   user_already_exists: "L'utilisateur existe déjà",
   childcare_already_exists: "Cette crèche existe déjà",
   badRequest: "Mauvaise requête, veuillez contacter l'administrateur",

   login_page_title: "Page de connexion",
   register_page_title: "Page d'inscription",
   childcare_management_page_title: "Gerer votre crèche",
   create_childcare_title: "Creer une crèche",
}

export const AppRegex = {
   email: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
   password: /^(?=.*[A-Z])(?=.*[!@#$%^&*(),.?":{}|<>])(?=.*[0-9])(?=.*[a-z]).{8,}$/,
   phoneNumber: /^\d{10}$/
}
