import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#fff',
        alignItems: 'center',
        justifyContent: 'center',
    },
    screenShell: {
        flex: 1,
        backgroundColor: '#f2f4f6',
        position: 'relative',
        overflow: 'hidden',
    },
    centeredContent: {
        flexGrow: 1,
        justifyContent: 'center',
        paddingHorizontal: 24,
        paddingVertical: 32,
    },
    heroCard: {
        width: '100%',
        maxWidth: 980,
        alignSelf: 'center',
        backgroundColor: '#fff',
        borderRadius: 24,
        padding: 24,
        borderWidth: 1,
        borderColor: '#e8e8e8',
        shadowColor: '#000',
        shadowOpacity: 0.08,
        shadowRadius: 10,
        elevation: 3,
    },
    heroTitle: {
        fontSize: 28,
        fontWeight: '800',
        color: '#1a1a1a',
        marginBottom: 8,
    },
    heroSubtitle: {
        fontSize: 14,
        color: '#777',
        marginBottom: 24,
    },
    roleGrid: {
        marginTop: 24,
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
    },
    roleCard: {
        width: '31%',
        minWidth: 220,
        backgroundColor: '#fff',
        borderRadius: 16,
        padding: 20,
        borderWidth: 1,
        borderColor: '#e8e8e8',
        marginBottom: 16,
        shadowColor: '#000',
        shadowOpacity: 0.04,
        shadowRadius: 6,
        elevation: 2,
    },
    roleIcon: {
        width: 48,
        height: 48,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: 20,
        fontWeight: '800',
        marginBottom: 16,
    },
    roleTitle: {
        fontSize: 17,
        fontWeight: '700',
        color: '#1a1a1a',
        marginBottom: 8,
    },
    roleText: {
        fontSize: 13,
        color: '#777',
        lineHeight: 20,
        marginBottom: 18,
    },
    roleCta: {
        fontSize: 13,
        fontWeight: '700',
    },
    decorativeBlob: {
        position: 'absolute',
        borderRadius: 999,
        opacity: 0.6,
    },
    footerText: {
        marginTop: 28,
        textAlign: 'center',
        color: '#bbb',
        fontSize: 12,
    },
    loginLayout: {
        flex: 1,
        flexDirection: 'row',
        backgroundColor: '#fff',
    },
    loginPanel: {
        flex: 1,
        paddingHorizontal: 36,
        paddingVertical: 32,
        justifyContent: 'center',
    },
    loginHero: {
        flex: 1,
        paddingHorizontal: 36,
        paddingVertical: 32,
        justifyContent: 'space-between',
    },
    heroBadge: {
        alignSelf: 'flex-start',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 999,
        backgroundColor: 'rgba(255,255,255,0.2)',
        marginBottom: 18,
    },
    heroBadgeText: {
        color: '#fff',
        fontSize: 12,
        fontWeight: '700',
    },
    heroTitleWhite: {
        fontSize: 32,
        fontWeight: '800',
        color: '#fff',
        marginBottom: 10,
    },
    heroTextWhite: {
        fontSize: 15,
        color: 'rgba(255,255,255,0.9)',
        lineHeight: 22,
    },
    backLink: {
        color: '#2A9D8F',
        fontSize: 14,
        fontWeight: '600',
        marginBottom: 20,
    },
    formTitle: {
        fontSize: 24,
        fontWeight: '800',
        color: '#1a1a1a',
        marginBottom: 6,
    },
    formSubtitle: {
        fontSize: 13,
        color: '#777',
        marginBottom: 18,
        lineHeight: 20,
    },
    formField: {
        marginBottom: 14,
    },
    fieldLabel: {
        fontSize: 12,
        color: '#555',
        marginBottom: 6,
        fontWeight: '600',
    },
    input: {
        borderWidth: 1,
        borderColor: '#dfe4ea',
        borderRadius: 12,
        paddingHorizontal: 14,
        paddingVertical: 12,
        fontSize: 14,
        backgroundColor: '#fff',
    },
    passwordContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#dfe4ea',
        borderRadius: 12,
        paddingRight: 10,
        backgroundColor: '#fff',
    },
    passwordInput: {
        flex: 1,
        paddingHorizontal: 14,
        paddingVertical: 12,
        fontSize: 14,
    },
    checkboxRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 16,
    },
    checkboxText: {
        fontSize: 12,
        color: '#666',
        marginLeft: 8,
    },
    primaryButton: {
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 12,
        paddingVertical: 13,
        marginTop: 6,
    },
    primaryButtonText: {
        color: '#fff',
        fontWeight: '700',
        fontSize: 15,
    },
    secondaryButton: {
        borderWidth: 1,
        borderColor: '#e5e5e5',
        borderRadius: 12,
        paddingVertical: 12,
        alignItems: 'center',
        marginTop: 10,
        backgroundColor: '#fafafa',
    },
    secondaryButtonText: {
        color: '#444',
        fontWeight: '600',
        fontSize: 14,
    },
    helperText: {
        fontSize: 13,
        color: '#777',
        marginTop: 12,
        lineHeight: 19,
    },
    dashboardScreen: {
        flex: 1,
        backgroundColor: '#f2f4f6',
    },
    dashboardContainer: {
        flexGrow: 1,
        padding: 24,
    },
    dashboardHeader: {
        marginBottom: 20,
    },
    dashboardTitle: {
        fontSize: 28,
        fontWeight: '800',
        color: '#1a1a1a',
        marginBottom: 4,
    },
    dashboardSubtitle: {
        fontSize: 13,
        color: '#777',
        marginBottom: 16,
    },
    dashboardGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
    },
    dashboardCard: {
        width: '31%',
        minWidth: 220,
        backgroundColor: '#fff',
        borderRadius: 16,
        borderWidth: 1,
        borderColor: '#e8e8e8',
        padding: 18,
        marginBottom: 16,
        shadowColor: '#000',
        shadowOpacity: 0.04,
        shadowRadius: 6,
        elevation: 2,
    },
    dashboardCardIcon: {
        width: 42,
        height: 42,
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 12,
    },
    dashboardCardTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: '#1a1a1a',
        marginBottom: 6,
    },
    dashboardCardText: {
        fontSize: 13,
        color: '#777',
        lineHeight: 18,
    },
    sectionCard: {
        backgroundColor: '#fff',
        borderRadius: 16,
        padding: 16,
        borderWidth: 1,
        borderColor: '#e8e8e8',
        marginBottom: 16,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#1a1a1a',
        marginBottom: 6,
    },
    sectionSubtitle: {
        fontSize: 13,
        color: '#777',
        marginBottom: 12,
    },
    tableHeaderRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingBottom: 10,
        borderBottomWidth: 1,
        borderBottomColor: '#f0f0f0',
        marginBottom: 10,
    },
    tableHeaderText: {
        fontSize: 12,
        fontWeight: '700',
        color: '#777',
        flex: 1,
    },
    managementCard: {
        borderWidth: 1,
        borderColor: '#ececec',
        borderRadius: 14,
        padding: 14,
        backgroundColor: '#fcfcfc',
        marginBottom: 12,
    },
    managementTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: '#1a1a1a',
        marginBottom: 4,
    },
    managementText: {
        fontSize: 13,
        color: '#777',
        lineHeight: 20,
        marginBottom: 8,
    },
    actionRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        marginTop: 8,
    },
    actionButton: {
        backgroundColor: '#f0f6ff',
        borderRadius: 999,
        paddingHorizontal: 12,
        paddingVertical: 8,
        marginRight: 8,
        marginBottom: 8,
    },
    actionButtonText: {
        color: '#2A9D8F',
        fontSize: 12,
        fontWeight: '700',
    },
    manage_menu: {
        alignContent: 'space-between',
        backgroundColor: '#fff',
        alignItems: 'center',
        justifyContent: 'space-between',
        flexDirection: 'row',
        width: "100%",
        paddingLeft: 5,
        paddingRight: 5,
    },
    modal_container: {
        height: "30%",
        backgroundColor: '#fff',
        alignItems: 'center',
        justifyContent: 'center',
    },
    h1: {
        fontSize: 22,
        fontWeight: 'bold',
    },
    h2: {
        fontSize: 20,
        fontWeight: 'bold',
    },
    h3: {
        fontSize: 18,
        fontWeight: 'bold',
    },

    form_container: {
        backgroundColor: '#fff',
        width: "80%",
        alignItems: 'flex-start',
        justifyContent: 'flex-start',
    },
    form_text: {
        fontSize: 11,
    },
    form_text_input: {
        margin: 5,
        padding: 15,
        borderWidth: 1,
        borderRadius: 4,
        width: "100%",
        borderColor: "black"
    },
    form_text_input_2: {
        margin: 5,
        borderWidth: 1,
        borderRadius: 4,
        width: "100%",
        backgroundColor: "white",
        borderColor: "black"
    },
    aic: {
        alignItems: "center",
        width: "100%",
    },
    gridContainer: {
        width: 220,
    },
    table: {
        width: "100%",
    },
    tableTitle: {
        backgroundColor: "#FDD49E",
        paddingHorizontal: 10,
        paddingVertical: 5,
        borderRadius: 5,
        elevation: 2,
        shadowColor: "#000",
        marginBottom: 5,
    },
    tableHeader: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-around",
        padding: 10,
        fontFamily: "Arial",
    },
    tableHeading: {
        flex: 1,
        fontSize: 16,
    },
    tableRow: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },
    tableRowText: {
        flex: 1,
    },
    picker: { 
        backgroundColor: 'rgb(211, 211, 211)', 
        elevation: 1, 
        zIndex: 22, 
        width: '100%', 
        marginTop: 60, 
        position: 'absolute' 
    },
    button_principal: {
        backgroundColor: "#FDD49E",
        margin: 5,
        color: "#FDD49E",
        alignItems: 'center',
        padding: 5,
        minWidth: "60%",
        minHeight: "8%",
        justifyContent: "center",
        borderRadius: 5,
    },
    button_menu: {
        backgroundColor: "#FDD49E",
        color: "#FDD49E",
        alignItems: 'center',
        padding: 5,
        minWidth: "30%",
        minHeight: "8%",
        justifyContent: "center",
        borderRadius: 5,
    },
    text_secondary: {
        color: "blue",
        margin: 5,
        fontSize: 14,
    },
    text_error: {
        color: "red",
        fontSize: 14,
    },
    separator: {
        marginVertical: 8,
        margin: 10,
        minWidth: "80%",
        borderBottomColor: '#737373',
        borderBottomWidth: StyleSheet.hairlineWidth,
    },
});